[package]
name = "advent-25"
version = "0.1.0"
edition = "2024"

[dependencies]
itertools = "0.14"
pathfinding = "4"
rayon = "1"
good_lp = { version = "1", features = [
  "scip",
  "scip_bundled",
], default-features = false }
